<?php
	define ('BASE_FOLDER', 			realpath(dirname(__FILE__, 4)));
	define ('LOGINS_FOLDER', 		BASE_FOLDER.'/logins');
	define ('FILES_FOLDER', 		BASE_FOLDER.'/html/files');
	define ('PDF_FOLDER', 			BASE_FOLDER.'/pdf');
	define ('IP_FILE_EXT',			'ip');

	define('ACTION', 					'action');
	define('AXES', 						'axes');
	define('CHARGE_PROJET', 	'chargeProjet');
	define('CONSTANTS', 			'constants');
	define('CONNECTE', 				'connecte');
	define('CREER_VERSION', 	'creerVersion');
	define('DIRECTIONS',		 	'directions');
	define('DEBUG',		 				'DEBUG');
	define('DROITS',		 			'droits');
	define('DROITS_PROJETS',	'droitsProjets');
	define('ERROR', 					'error');
	define('ETAPES', 					'etapes');
	define('EXTENSION',				'ext');
	define('FICHIER_UPLOAD',	'uploadfile');
	define('FINANCEMENT',			'financement');
	define('FULL_NAME', 			'fullName');
	define('INFOS_FICHIERS',	'infosFichiers');
	define('INSTANCES',				'instances');
	define('IPUSER', 					'ipUser');
	define('IS_LAST_VERSION', 'isLastVersion');
	define('LISTE_PROJETS',		'listeProjets');
	define('LOGIN', 					'login');
	define('LOGOUT', 					'logout');
	define('MESSAGES',				'messages');
	define('NOM_FICHIER', 		'nom_fichier');
	define('NOM_FICHIER_FS', 	'nom_fichier_fs');
	define('NUM_FICHIER', 		'num_fichier');
	define('NUM_PROJET', 			'num_projet');
	define('PASSWORD', 				'password');
	define('PRECEDENT', 			'precedent');
	define('PROJET', 					'projet');
	define('SAUVE_PROJET', 		'sauveProjet');
	define('SESSION_USER', 		'sessionUser');
	define('SOUS_AXES', 			'sousAxes');
	define('SUCCESS',			 		'success');
	define('SUIVANT',			 		'suivant');
	define('TYPES_ETAPES', 		'typesEtapes');
	define('UPLOAD', 					'upload');
	define('USER', 						'user');
	define('UTILISATEURS',		'utilisateurs');
	define('VALIDE_PROJET',		'valideProjet');